<h1>Create User</h1>
<?php 
$form = $this->form;
$form->prepare();
// Assuming the "contact/process" route exist...
$form->setAttribute('action', $this->url('application/default',
    array(
        'controller' => 'User',
        'action' => 'create'
    )
));
// Set the method attribute for the form
$form->setAttribute('method','post');

echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();
